/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.TableModel;

/**
 *
 * @author Luís Alves
 */
public class ConsultarAlunos extends javax.swing.JFrame {

    private TableModel tableModel;

    /**
     * Creates new form ConsultarAlunos
     */
    public ConsultarAlunos(TableModel modelo) {
        this.tableModel = modelo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tabela_Socios = new javax.swing.JTable();
        mainMenu = new javax.swing.JMenuBar();
        menu_Gestao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela_Socios.setModel(tableModel);
        tabela_Socios.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabela_SociosPropertyChange(evt);
            }
        });
        scrollPane.setViewportView(tabela_Socios);

        menu_Gestao.setText("Adicionar Sócio");
        mainMenu.add(menu_Gestao);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabela_SociosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabela_SociosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tabela_SociosPropertyChange

    public void tabela_SociosSetModel(TableModel modelo) {
        tabela_Socios.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu menu_Gestao;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabela_Socios;
    // End of variables declaration//GEN-END:variables
}
